services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
            ###########################
            ### PROXY REQUIREMENTS ####
            ### FOR DEV ENVIRONMENT ###
            ###########################
            ### For connecting domain to DNSMASQ
            - 'test-jet-r.test:127.0.0.1'
        ports:
            ###########################
            ### PROXY REQUIREMENTS ####
            ### FOR DEV ENVIRONMENT ###
            ###########################
            ### For connecting domain to Proxy 8000
            - '${APP_PORT:-8000}:80'
            ###########################
            ### PROXY REQUIREMENTS ####
            ### FOR DEV ENVIRONMENT ###
            ###########################
            ### For connecting in lan 5000 and vire
            - '${VITE_PORT:-5001}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
networks:
    sail:
        driver: bridge
